<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Natasha Kang">

<title>Causality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="lect1_causality_files/libs/clipboard/clipboard.min.js"></script>
<script src="lect1_causality_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="lect1_causality_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="lect1_causality_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="lect1_causality_files/libs/quarto-html/popper.min.js"></script>
<script src="lect1_causality_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lect1_causality_files/libs/quarto-html/anchor.min.js"></script>
<link href="lect1_causality_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lect1_causality_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lect1_causality_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lect1_causality_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lect1_causality_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-and-motivation" id="toc-introduction-and-motivation" class="nav-link active" data-scroll-target="#introduction-and-motivation">Introduction and Motivation</a></li>
  <li><a href="#potential-outcomes" id="toc-potential-outcomes" class="nav-link" data-scroll-target="#potential-outcomes">Potential Outcomes</a></li>
  <li><a href="#random-assignment-and-rcts" id="toc-random-assignment-and-rcts" class="nav-link" data-scroll-target="#random-assignment-and-rcts">Random Assignment and RCTs</a></li>
  <li><a href="#covariates-and-heterogeneity" id="toc-covariates-and-heterogeneity" class="nav-link" data-scroll-target="#covariates-and-heterogeneity">Covariates and Heterogeneity</a></li>
  <li><a href="#causal-diagrams-and-rct-limits" id="toc-causal-diagrams-and-rct-limits" class="nav-link" data-scroll-target="#causal-diagrams-and-rct-limits">Causal Diagrams and RCT Limits</a></li>
  <li><a href="#observational-studies" id="toc-observational-studies" class="nav-link" data-scroll-target="#observational-studies">Observational Studies</a></li>
  <li><a href="#identification-by-conditioning" id="toc-identification-by-conditioning" class="nav-link" data-scroll-target="#identification-by-conditioning">Identification by Conditioning</a></li>
  <li><a href="#course-roadmap" id="toc-course-roadmap" class="nav-link" data-scroll-target="#course-roadmap">Course Roadmap</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Causality</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Natasha Kang </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Xiamen University, Chow Institute
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-and-motivation" class="level1">
<h1>Introduction and Motivation</h1>
<section id="what-is-causality" class="level2">
<h2 class="anchored" data-anchor-id="what-is-causality">What is Causality?</h2>
<ul>
<li>Causality is about understanding the <strong>cause-effect</strong> relationships in data.</li>
<li>It answers <strong>what-if</strong> questions:
<ul>
<li>What would happen if we intervene?</li>
<li>Would the outcome be different under an alternative scenario?</li>
</ul></li>
<li>Causal reasoning is central to <strong>economic analysis</strong>.</li>
</ul>
</section>
<section id="causal-questions-in-economics" class="level2">
<h2 class="anchored" data-anchor-id="causal-questions-in-economics">Causal Questions in Economics</h2>
<ul>
<li>Do smaller classes improve test scores?</li>
<li>Does more education lead to higher income?</li>
<li>Is there gender discrimination in the labor market?</li>
</ul>
<div class="fragment">
<ul>
<li>Causality: Action (Treatment) → Outcome<br>
</li>
<li>Causal effect: the impact on the outcome associated with a <em>ceteris paribus</em> change in the treatment.</li>
<li>Challenge: Treatment is often related to other factors that also affect the outcome.<br>
</li>
</ul>
</div>
</section>
<section id="whats-the-effect-of-hospital-on-health" class="level2">
<h2 class="anchored" data-anchor-id="whats-the-effect-of-hospital-on-health">What’s the Effect of Hospital on Health?</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>Sample Size</th>
<th>Mean Health</th>
<th>Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hospital</td>
<td>7,774</td>
<td>3.21</td>
<td>0.014</td>
</tr>
<tr class="even">
<td>No Hospital</td>
<td>90,049</td>
<td>3.93</td>
<td>0.003</td>
</tr>
</tbody>
</table>
<ul>
<li><em>Hospital</em> = hospitalized during past 12 months<br>
</li>
<li><em>Health status</em> = 1 (poor) to 5 (excellent)</li>
</ul>
</section>
<section id="are-hospitals-making-people-sicker" class="level2">
<h2 class="anchored" data-anchor-id="are-hospitals-making-people-sicker">Are Hospitals Making People Sicker?</h2>
<p><img src="images/what-confused.gif" width="300px" style="display: block; margin: auto;"></p>
</section>
<section id="are-hospitals-making-people-sicker-1" class="level2">
<h2 class="anchored" data-anchor-id="are-hospitals-making-people-sicker-1">Are Hospitals Making People Sicker?</h2>
<ul>
<li>Maybe, but people who go to the hospital are likely to be less healthy.
<ul>
<li>e.g., pre-existing medical conditions</li>
</ul></li>
<li>A direct comparison is misleading:
<ul>
<li>Other factors are not held constant.</li>
</ul></li>
<li>This is the <strong>selection problem</strong>: the sick are more likely to seek treatment.</li>
</ul>
</section>
<section id="association-causality" class="level2">
<h2 class="anchored" data-anchor-id="association-causality">Association ≠ Causality</h2>
<ul>
<li>In the hospital example, differences in health reflect both hospitalization <strong>and</strong> patients’ underlying health.</li>
<li>Observed differences may arise from <strong>selection</strong>, not from the effect of treatment itself.</li>
</ul>
<div class="fragment">
<ul>
<li>In general, statistical analysis uncovers <strong>associations</strong> in observed data.</li>
<li>The key question is: <strong>When does an association reflect a causal effect?</strong></li>
<li>To answer that, we need a <strong>formal framework</strong> for defining and reasoning about causality.</li>
</ul>
</div>
</section>
<section id="frameworks-for-causality" class="level2">
<h2 class="anchored" data-anchor-id="frameworks-for-causality">Frameworks for Causality</h2>
<ul>
<li><strong>Potential Outcomes Framework</strong>
<ul>
<li>Neyman (1923), Rubin (1974)</li>
<li>Compare potential outcomes under different treatments</li>
</ul></li>
<li><strong>Structural Causal Models (SCM)</strong>
<ul>
<li>Pearl (2009)</li>
<li>Use directed acyclic graphs (DAGs) to model causal paths</li>
</ul></li>
<li>These frameworks are mathematically related — we’ll use both.</li>
</ul>
</section>
</section>
<section id="potential-outcomes" class="level1">
<h1>Potential Outcomes</h1>
<section id="potential-outcomes-one-unit-two-worlds" class="level2">
<h2 class="anchored" data-anchor-id="potential-outcomes-one-unit-two-worlds">Potential Outcomes: One Unit, Two Worlds</h2>
<ul>
<li><span class="math inline">\(Y(1)\)</span>: potential outcome if treated<br>
</li>
<li><span class="math inline">\(Y(0)\)</span>: potential outcome if untreated</li>
</ul>
<p><img src="images/TwoRoadsDiverge.png" style="width: 100%; max-width: 900px; display: block; margin: auto;"></p>
</section>
<section id="the-potential-outcomes-framework" class="level2">
<h2 class="anchored" data-anchor-id="the-potential-outcomes-framework">The Potential Outcomes Framework</h2>
<ul>
<li>General setup: <span class="math display">\[d \rightarrow Y(d)\]</span></li>
<li><strong>SUTVA</strong> (Stable Unit Treatment Value Assumption):
<ul>
<li><strong>Consistency</strong>: <span class="math inline">\(Y = Y(D)\)</span>, where <span class="math inline">\(D\)</span> is the actual assigned treatment.</li>
<li><strong>No interference</strong>: the potential outcomes for any unit should not be affected by the treatment assigned to other units.
<ul>
<li>i.e.&nbsp;no <em>spillover</em> effects.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="does-sutva-hold" class="level2">
<h2 class="anchored" data-anchor-id="does-sutva-hold">Does SUTVA Hold?</h2>
<ul>
<li><p><strong>Treatment</strong>: Job training program; <strong>Outcome</strong>: Individual productivity (units completed per shift)</p></li>
<li><p><strong>Scenario 1</strong>:<br>
Workers operate independently at personal workstations. Tasks are assigned individually, and there’s no collaboration. However, trained and untrained workers often interact informally during breaks.</p></li>
<li><p><strong>Scenario 2</strong>:<br>
Workers are assigned to 4-person teams operating sequential assembly lines. Each member is fixed to one station (A, B, C, or D) for the entire shift. Output is tracked individually as the number of units completed at each station.</p></li>
<li><p><strong>Question</strong>:<br>
In which scenario(s), if any, would it be reasonable to assume SUTVA holds?</p></li>
</ul>
<hr>
</section>
<section id="does-sutva-hold-1" class="level2">
<h2 class="anchored" data-anchor-id="does-sutva-hold-1">Does SUTVA Hold?</h2>
<ul>
<li>A worker assigned to training arrives late and misses half the session.</li>
<li><strong>Question</strong>: Can their observed outcome be treated as the potential outcome under treatment?
<ul>
<li>A. Yes<br>
</li>
<li>B. No</li>
</ul></li>
</ul>
<hr>
</section>
<section id="revisiting-hospital-and-health" class="level2">
<h2 class="anchored" data-anchor-id="revisiting-hospital-and-health">Revisiting Hospital and Health</h2>
<ul>
<li>Outcome of Interest: <span class="math inline">\(Y\)</span>, health status</li>
<li>Treatment: hospital <span class="math display">\[
D = \begin{cases}
1, &amp; \text{if hospitalized} \\
0, &amp; \text{if not hospitalized}
\end{cases}
\]</span></li>
<li>Define potential outcomes:
<ul>
<li><span class="math inline">\(Y(1)\)</span>: health status if hospitalized<br>
</li>
<li><span class="math inline">\(Y(0)\)</span>: health status if not hospitalized</li>
</ul></li>
<li>Observed outcome: <span class="math inline">\(Y = D \cdot Y(1) + (1 - D) \cdot Y(0)\)</span></li>
</ul>
<hr>
</section>
<section id="average-treatment-effect-ate" class="level2">
<h2 class="anchored" data-anchor-id="average-treatment-effect-ate">Average Treatment Effect (ATE)</h2>
<ul>
<li><p>Ideally, we’d like to know the <strong>individual causal effect</strong>:<br>
<span class="math display">\[
Y(1) - Y(0)
\]</span></p></li>
<li><p>But we <strong>can’t observe both</strong> potential outcomes for the same person.</p></li>
<li><p>So instead, we compute the <strong>average treatment effect</strong>: <span class="math display">\[
\text{ATE} = \mathbb{E}[Y(1) - Y(0)]
\]</span></p></li>
<li><p>With certain assumptions, we can <strong>estimate ATE from observed data</strong>.</p></li>
</ul>
<hr>
</section>
<section id="what-can-be-estimated" class="level2">
<h2 class="anchored" data-anchor-id="what-can-be-estimated">What Can Be Estimated?</h2>
<ul>
<li>Can we estimate the following?
<ol type="1">
<li><span class="math inline">\(Y(1) - Y(0)\)</span><br>
</li>
<li><span class="math inline">\(\mathbb{E}[Y \mid D=1]\)</span><br>
</li>
<li><span class="math inline">\(\mathbb{E}[Y \mid D=0]\)</span><br>
</li>
<li><span class="math inline">\(\mathbb{E}[Y(1) \mid D=0]\)</span><br>
</li>
<li><span class="math inline">\(\mathbb{E}[Y(0) \mid D=1]\)</span><br>
</li>
<li><span class="math inline">\(\mathbb{E}[Y(1) \mid D=1]\)</span><br>
</li>
<li><span class="math inline">\(\mathbb{E}[Y(0) \mid D=0]\)</span></li>
</ol></li>
</ul>
<hr>
</section>
<section id="decomposing-observed-differences" class="level2">
<h2 class="anchored" data-anchor-id="decomposing-observed-differences">Decomposing Observed Differences</h2>
<div class="fragment">
<p><span class="math display">\[
\mathbb{E}[Y \mid D = 1] - \mathbb{E}[Y \mid D = 0]
\]</span> <strong>=APE</strong>: Average Predictive Effect</p>
</div>
<div class="fragment">
<p><span class="math display">\[
= \mathbb{E}[Y(1) \mid D = 1] - \mathbb{E}[Y(0) \mid D = 1]
\]</span> <strong>= ATT</strong>: Average Treatment Effect on the Treated</p>
</div>
<div class="fragment">
<p><span class="math display">\[
\quad + \mathbb{E}[Y(0) \mid D = 1] - \mathbb{E}[Y(0) \mid D = 0]
\]</span> <strong>= Selection Bias</strong></p>
</div>
<hr>
</section>
</section>
<section id="random-assignment-and-rcts" class="level1">
<h1>Random Assignment and RCTs</h1>
<section id="random-assignment" class="level2">
<h2 class="anchored" data-anchor-id="random-assignment">Random Assignment</h2>
<ul>
<li>If treatment <span class="math inline">\(D\)</span> is randomly assigned: <span class="math display">\[
D \perp (Y(0), Y(1)), \quad 0 &lt; P(D=1) &lt; 1
\]</span></li>
<li>Then <span class="math display">\[
\mathbb{E}[Y \mid D=1] - \mathbb{E}[Y \mid D=0] = \text{ATE}
\]</span></li>
</ul>
<div class="fragment">
<ul>
<li><strong>Random assignment</strong> breaks the link between treatment and potential outcomes — eliminating selection bias.</li>
<li>Though often infeasible in observational studies, it provides a <strong>benchmark</strong> for causal inference.</li>
</ul>
</div>
<hr>
</section>
<section id="randomized-controlled-trial-rct" class="level2">
<h2 class="anchored" data-anchor-id="randomized-controlled-trial-rct">Randomized Controlled Trial (RCT)</h2>
<ul>
<li>An RCT <strong>implements</strong> random assignment in practice.</li>
<li>Subjects are randomly assigned to:
<ul>
<li>Treatment group: <span class="math inline">\(D = 1\)</span></li>
<li>Control group: <span class="math inline">\(D = 0\)</span></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p>With random assignment: <span class="math display">\[
\text{ATE} = \mathbb{E}[Y \mid D=1] - \mathbb{E}[Y \mid D=0]
\]</span></p></li>
<li><p>But <strong>large samples</strong> are crucial:</p>
<ul>
<li>By the <strong>Law of Large Numbers</strong>, idiosyncratic differences average out.</li>
<li>Ensures treated and control groups are <strong>balanced</strong> on both observed and unobserved factors.</li>
</ul></li>
</ul>
</div>
<hr>
</section>
<section id="from-identification-to-estimation" class="level2">
<h2 class="anchored" data-anchor-id="from-identification-to-estimation">From Identification to Estimation</h2>
<div class="fragment">
<ul>
<li><strong>Random assignment</strong> identifies the causal effect (ATE) as a difference in observed means across groups.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>But this identification is at the population level.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>In practice, we rely on <strong>sample data</strong>, so we must estimate the ATE and quantify uncertainty.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>This brings us to <strong>statistical inference</strong>:
<ul>
<li>Estimate population means using <strong>sample averages</strong>.</li>
<li>Assess precision using <strong>standard errors</strong>.</li>
</ul></li>
</ul>
</div>
<hr>
</section>
<section id="statistical-inference-group-means" class="level2">
<h2 class="anchored" data-anchor-id="statistical-inference-group-means">Statistical Inference: Group Means</h2>
<ul>
<li><p>Suppose we have i.i.d. data from an RCT:<br>
<span class="math display">\[
\{(Y_i, D_i)\}_{i=1}^n
\]</span></p></li>
<li><p>For each group <span class="math inline">\(d \in \{0, 1\}\)</span>, define the population mean: <span class="math display">\[
\theta_d = \mathbb{E}[Y \mid D = d]
\]</span></p></li>
<li><p>The sample mean is:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
\widehat{\theta}_d =
\frac{\sum_{i=1}^n Y_i \cdot \mathbf{1}(D_i = d)}{\sum_{i=1}^n \mathbf{1}(D_i = d)} = \frac{1}{n_d} \sum_{i=1}^n Y_i \cdot \mathbf{1}(D_i = d)
\]</span></p>
</div>
<div class="fragment">
<ul>
<li>Since treatment is randomly assigned: <span class="math display">\[
\{Y_i \cdot \mathbf{1}(D_i = d)\}_{i=1}^n \quad \text{are i.i.d. with finite variance}
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Then by CLT (conditional on <span class="math inline">\(D\)</span>), as <span class="math inline">\(n_d \to \infty\)</span>: <span class="math display">\[
\sqrt{n_d}(\widehat{\theta}_d - \theta_d)
\overset{d}{\longrightarrow}
\mathrm{N}(0, \sigma_d^2)
\]</span> where <span class="math inline">\(\sigma_d^2 = \mathrm{Var}(Y \mid D = d)\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Under random assignment, <span class="math inline">\(n_d/n \to P(D = d)\)</span>. So we can write: <span class="math display">\[
\sqrt{n}(\widehat{\theta}_d - \theta_d)
\overset{d}{\longrightarrow}
\mathrm{N} \left(0, \frac{\mathrm{Var}(Y \mid D = d)}{P(D = d)} \right)
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Moreover, under random assignment, groups are independent: <span class="math display">\[
\sqrt{n}
\begin{pmatrix}
\widehat{\theta}_1 - \theta_1 \\
\widehat{\theta}_0 - \theta_0
\end{pmatrix}
\overset{d}{\longrightarrow}
\mathrm{N}
\left(
\begin{pmatrix}
0 \\ 0
\end{pmatrix},
\begin{pmatrix}
\frac{\sigma_1^2}{p_1} &amp; 0 \\
0 &amp; \frac{\sigma_0^2}{p_0}
\end{pmatrix}
\right)
\]</span></li>
</ul>
</div>
</section>
<section id="inference-for-ate-difference-in-means" class="level2">
<h2 class="anchored" data-anchor-id="inference-for-ate-difference-in-means">Inference for ATE: Difference in Means</h2>
<ul>
<li>We want to test: <span class="math display">\[
H_0: \theta_1 - \theta_0 = 0 \quad \text{vs} \quad H_1: \theta_1 - \theta_0 \neq 0
\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>From joint asymptotic normality: <span class="math display">\[
\sqrt{n} \left[ (\widehat{\theta}_1 - \widehat{\theta}_0) - (\theta_1 - \theta_0) \right]
\overset{d}{\longrightarrow}
\mathrm{N}\left(0,\; \frac{\sigma_1^2}{p_1} + \frac{\sigma_0^2}{p_0} \right)
\]</span> For <span class="math inline">\(n\)</span> large, <span class="math display">\[(\widehat{\theta}_1 - \widehat{\theta}_0) \;\approx\; \mathrm{N}\left( \theta_1- \theta_0,\;\frac{\sigma_1^2}{n_1} + \frac{\sigma_0^2}{n_0} \right)\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>We estimate the variance using sample analogues: <span class="math display">\[
\widehat{\sigma}_d^2 = \frac{1}{n_d - 1} \sum_{i: D_i = d} (Y_i - \widehat{\theta}_d)^2
\]</span></p>
<p>and construct the standard error: <span class="math display">\[
\widehat{\mathrm{SE}}^2 = \frac{\widehat{\sigma}_1^2}{n_1} + \frac{\widehat{\sigma}_0^2}{n_0}
\]</span></p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>The test statistic is:</li>
</ul>
</div>
<div class="fragment">
<p><span class="math display">\[T = \frac{\widehat{\theta}_1 - \widehat{\theta}_0}{\widehat{\mathrm{SE}}}\;\overset{H_0}{\sim}\; \mathrm{N}(0, 1)\]</span></p>
</div>
</section>
<section id="estimating-causal-effect-an-rct-example" class="level2">
<h2 class="anchored" data-anchor-id="estimating-causal-effect-an-rct-example">Estimating Causal Effect: An RCT Example</h2>
<p><strong>Scenario</strong>: Evaluating the effect of a new fertilizer on crop yield through a randomized controlled trial (RCT).</p>
<ul>
<li>▶️ <strong>Treatment Group</strong>: 50 farms use the new fertilizer.<br>
</li>
<li>▶️ <strong>Control Group</strong>: 50 farms use the standard fertilizer.</li>
</ul>
<table style="margin: auto; text-align: center;">
<thead>
<tr>
<th>
Group
</th>
<th>
Sample Size
</th>
<th>
Mean Yield
</th>
<th>
Std. Dev.
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Treatment
</td>
<td>
50
</td>
<td>
1800 kg/ha
</td>
<td>
150 kg/ha
</td>
</tr>
<tr>
<td>
Control
</td>
<td>
50
</td>
<td>
1650 kg/ha
</td>
<td>
140 kg/ha
</td>
</tr>
</tbody>
</table>
</section>
<section id="estimating-causal-effect-analysis" class="level2">
<h2 class="anchored" data-anchor-id="estimating-causal-effect-analysis">Estimating Causal Effect: Analysis</h2>
<ol type="1">
<li><strong>Difference in Means (Treatment Effect)</strong>:</li>
</ol>
<p><span class="math display">\[
\text{ATE} = \bar{Y}_T - \bar{Y}_C = 1800 - 1650 = 150 \text{ kg/ha}
\]</span></p>
<ol start="2" type="1">
<li><strong>Compute the test statistic</strong>:</li>
</ol>
<p><span class="math display">\[
t = \frac{\bar{Y}_T - \bar{Y}_C}{\sqrt{\frac{s_T^2}{n_T} + \frac{s_C^2}{n_C}}}
= \frac{150}{\sqrt{\frac{150^2}{50} + \frac{140^2}{50}}}
= \frac{150}{29.10} \approx 5.15
\]</span></p>
</section>
<section id="estimating-causal-effect-inference" class="level2">
<h2 class="anchored" data-anchor-id="estimating-causal-effect-inference">Estimating Causal Effect: Inference</h2>
<ol start="3" type="1">
<li><strong>Hypotheses</strong>:</li>
</ol>
<ul>
<li><span class="math inline">\(H_0\)</span>: The fertilizer has no effect (<span class="math inline">\(\mu_T - \mu_C = 0\)</span>).<br>
</li>
<li><span class="math inline">\(H_1\)</span>: The fertilizer affects yield (<span class="math inline">\(\mu_T - \mu_C \ne 0\)</span>).</li>
</ul>
<ol start="4" type="1">
<li><strong>Conclusion</strong>:</li>
</ol>
<ul>
<li><span class="math inline">\(t = 5.15\)</span> is highly significant (critical value at 5% level is 1.96).</li>
<li>✅ Reject <span class="math inline">\(H_0\)</span>: The fertilizer increases crop yield by approximately <strong>150 kg/ha</strong>.</li>
</ul>
</section>
</section>
<section id="covariates-and-heterogeneity" class="level1">
<h1>Covariates and Heterogeneity</h1>
<section id="covariates-and-heterogeneity-1" class="level2">
<h2 class="anchored" data-anchor-id="covariates-and-heterogeneity-1">Covariates and Heterogeneity</h2>
<ul>
<li><p>So far, we’ve focused on the <strong>average treatment effect (ATE)</strong> across the whole sample.</p></li>
<li><p>But individuals differ — age, education, baseline health, etc.</p></li>
</ul>
<div class="fragment">
<ul>
<li>These <strong>observable characteristics</strong> are often included in analysis as <strong>covariates</strong>, to explore <strong>differences in treatment effects</strong> across subgroups.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>This motivates studying <strong>treatment effect heterogeneity</strong>:
<ul>
<li>Who benefits more?</li>
<li>Are there subgroups where treatment is less effective?</li>
</ul></li>
</ul>
</div>
</section>
<section id="conditional-effects-cate" class="level2">
<h2 class="anchored" data-anchor-id="conditional-effects-cate">Conditional Effects: CATE</h2>
<ul>
<li><strong>Conditional Average Treatment Effect (CATE)</strong>: <span class="math display">\[
  \mathbb{E}[Y(1) - Y(0) \mid W]
  \]</span></li>
</ul>
<div class="fragment">
<ul>
<li>But we never observe both <span class="math inline">\(Y(1)\)</span> and <span class="math inline">\(Y(0)\)</span>. Instead only observe <span class="math display">\[
\mathbb{E}[Y \mid D=1, W] - \mathbb{E}[Y \mid D=0, W]
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>If treatment is randomly assigned<br>
<span class="math display">\[
D \;\perp\!\!\!\perp\; \left( Y(0), Y(1), W \right),
\quad \text{with } 0 &lt; P(D = 1) &lt; 1,
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Then the <strong>Conditional Average Treatment Effect (CATE)</strong> is identified: <span class="math display">\[
\mathbb{E}[Y(1) - Y(0) \mid W]
= \mathbb{E}[Y \mid D = 1, W] - \mathbb{E}[Y \mid D = 0, W]
\]</span></li>
</ul>
</div>
</section>
<section id="testing-covariate-balance" class="level2">
<h2 class="anchored" data-anchor-id="testing-covariate-balance">Testing Covariate Balance</h2>
<ul>
<li>The random assignment assumption implies <strong>covariate balance</strong>, i.e.&nbsp;the distribution of covariates is the same across treatment and control groups: <span class="math display">\[
W \mid D = 1 \;\overset{d}{=}\; W \mid D = 0
\]</span></li>
</ul>
<div class="fragment">
<p>and equivalently, <span class="math display">\[
D \mid W \;\overset{d}{=}\; D
\]</span></p>
</div>
<div class="fragment">
<p>A useful implication is that <span class="math inline">\(D\)</span> is <strong>not predictable</strong> by <span class="math inline">\(W\)</span>: <span class="math display">\[
\mathbb{E}[D \mid W] = \mathbb{E}[D]
\]</span></p>
<p>which can be tested using a regression of <span class="math inline">\(D\)</span> on <span class="math inline">\(W\)</span>.</p>
</div>
</section>
</section>
<section id="causal-diagrams-and-rct-limits" class="level1">
<h1>Causal Diagrams and RCT Limits</h1>
<section id="drawing-rcts-via-causal-diagrams" class="level2">
<h2 class="anchored" data-anchor-id="drawing-rcts-via-causal-diagrams">Drawing RCTs via Causal Diagrams</h2>
<ul>
<li><strong>Causal diagrams</strong> (DAGs) provide a graphical language for representing causal relationships.</li>
<li>Nodes represent variables; directed edges represent direct causal effects.</li>
<li>DAGs help us reason about identification, confounding, and when causal effects can be estimated from data.</li>
<li>In a randomized experiment, treatment ( D ) is assigned independently of all covariates — so <span class="math inline">\(W \not \! \rightarrow D\)</span>.</li>
</ul>
</section>
<section id="limitations-of-rcts" class="level2">
<h2 class="anchored" data-anchor-id="limitations-of-rcts">Limitations of RCTs</h2>
<ul>
<li><strong>Violations of SUTVA:</strong>
<ul>
<li><em>Spillover effects</em> — e.g.&nbsp;vaccination may protect others via herd immunity.</li>
<li><em>Equilibrium effects</em> — e.g.&nbsp;the earnings return to college may depend on how many people get degrees:
<ul>
<li>In small-scale trials: no effect on market wages.</li>
<li>At scale: wages may adjust, reducing the college premium.</li>
</ul></li>
</ul></li>
<li><strong>Ethical concerns:</strong>
<ul>
<li>Some treatments cannot be randomly assigned — e.g.&nbsp;smoking, pollution, trauma.</li>
</ul></li>
<li><strong>Practical constraints:</strong>
<ul>
<li>RCTs can be costly, time-consuming, or infeasible in many settings.</li>
</ul></li>
</ul>
</section>
</section>
<section id="observational-studies" class="level1">
<h1>Observational Studies</h1>
<section id="when-treatment-isnt-random" class="level2">
<h2 class="anchored" data-anchor-id="when-treatment-isnt-random">When Treatment Isn’t Random</h2>
<ul>
<li><p>In observational studies, treatment is often influenced by factors that also affect the outcome.</p></li>
<li><p>Do hospitals improve health?<br>
We observe health outcomes and hospitalization status —<br>
but sicker individuals are more likely to be hospitalized.</p></li>
<li><p>This makes it hard to separate the effect of hospitalization from the effect of underlying medical condition.</p></li>
</ul>
</section>
</section>
<section id="identification-by-conditioning" class="level1">
<h1>Identification by Conditioning</h1>
<section id="recovering-causality" class="level2">
<h2 class="anchored" data-anchor-id="recovering-causality">Recovering Causality</h2>
<p>To recover causal effects from observational data, we rely on two key assumptions:</p>
<div class="fragment">
<section id="conditional-ignorability-unconfoundedness" class="level3">
<h3 class="anchored" data-anchor-id="conditional-ignorability-unconfoundedness">1. Conditional Ignorability (Unconfoundedness)</h3>
<p><span class="math display">\[
D \perp Y(d) \mid X
\]</span></p>
<p>Once we condition on covariates <span class="math inline">\(X\)</span>, treatment is “as if” randomly assigned.<br>
This rules out confounding by observed variables.</p>
</section>
</div>
<div class="fragment">
<section id="overlap-common-support" class="level3">
<h3 class="anchored" data-anchor-id="overlap-common-support">2. Overlap (Common Support)</h3>
<p><span class="math display">\[
0 &lt; P(D = 1 \mid X) &lt; 1
\]</span></p>
<p>For every covariate profile, we observe both treated and untreated individuals.</p>
</section>
</div>
</section>
<section id="identification-by-conditioning-1" class="level2">
<h2 class="anchored" data-anchor-id="identification-by-conditioning-1">Identification by Conditioning</h2>
<p><strong>Before Conditioning</strong><br>
<img src="images/ConIgnorability_1.png" style="display: block; margin: 1em auto; width: 100%; max-width: 900px;"></p>
<p><strong>After Conditioning on Covariates</strong><br>
<img src="images/ConIgnorability_2.png" style="display: block; margin: 1em auto; width: 100%; max-width: 900px;"></p>
</section>
<section id="what-the-assumptions-let-us-do" class="level2">
<h2 class="anchored" data-anchor-id="what-the-assumptions-let-us-do">What the Assumptions Let Us Do</h2>
<ul>
<li>Under <strong>Conditional Ignorability</strong> and <strong>Overlap</strong>, we can identify causal effects using observed data.</li>
</ul>
<div class="fragment">
<ul>
<li>Specifically, we can equate observed and counterfactual conditional expectations: <span class="math display">\[
\mathbb{E}[Y \mid D = d, X] = \mathbb{E}[Y(d) \mid X]
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>So the difference in observed outcomes conditional on <span class="math inline">\(X\)</span>: <span class="math display">\[
\pi(X) = \mathbb{E}[Y \mid D = 1, X] - \mathbb{E}[Y \mid D = 0, X]
\]</span> equals the <strong>Conditional Average Treatment Effect (CATE)</strong>: <span class="math display">\[
\delta(X) = \mathbb{E}[Y(1) \mid X] - \mathbb{E}[Y(0) \mid X]
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Averaging over ( X ), we recover the ATE: <span class="math display">\[
\mathbb{E}[\delta(X)] = \mathbb{E}[\pi(X)] = \text{ATE}
\]</span></li>
</ul>
</div>
</section>
</section>
<section id="course-roadmap" class="level1">
<h1>Course Roadmap</h1>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next?</h2>
<p><strong>Course Roadmap: Steps in Empirical Analysis</strong></p>
<ol type="1">
<li><span style="color:gray;"><strong>Question</strong>: Define the research question or problem.</span><br>
</li>
<li><span style="color:MidnightBlue;"><strong>Econometric Model</strong></span>: Specify the model for data analysis.<br>
</li>
<li><span style="color:gray;"><strong>Formulate a Hypothesis</strong>: Develop a testable hypothesis of interest.</span><br>
</li>
<li><span style="color:gray;"><strong>Estimate the Model with Data</strong>: Use econometric methods to estimate model parameters.</span><br>
</li>
<li><span style="color:gray;"><strong>Inference/Hypothesis Testing</strong>: Perform statistical tests for making inferences about the population.</span></li>
</ol>
</section>
<section id="econometric-model-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="econometric-model-linear-regression">Econometric Model: Linear Regression</h2>
<ul>
<li><p><strong>Why is regression essential?</strong></p>
<ul>
<li>Despite its simplicity, it is highly versatile and widely used in empirical analysis.</li>
<li>Bridges theory and evidence, allowing us to test hypotheses and validate economic models.</li>
<li>Provides insights into both <strong>causal relationships</strong> and <strong>predictive patterns</strong>.</li>
</ul></li>
<li><p>Linear regression is used for:</p>
<ul>
<li><strong>Causality</strong>: Estimating the average treatment effect.</li>
<li><strong>Prediction</strong>: Forecasting outcomes based on observables.</li>
</ul></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>